// flow-typed signature: d757bdb2576173d6f7ea739f561166ec
// flow-typed version: <<STUB>>/@slack/client_v5.0.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@slack/client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@slack/client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@slack/client/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@slack/client/dist/index.js' {
  declare module.exports: $Exports<'@slack/client/dist/index'>;
}
