// flow-typed signature: 9c9b7d50320525fed2d1f06276ecf0c2
// flow-typed version: <<STUB>>/@packtracker/webpack-plugin_v1.1.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@packtracker/webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@packtracker/webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@packtracker/webpack-plugin/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@packtracker/webpack-plugin/index' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin'>;
}
declare module '@packtracker/webpack-plugin/index.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin'>;
}
declare module '@packtracker/webpack-plugin/lib.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin/lib'>;
}
