// flow-typed signature: fd4afe455f7e943a44d4a01d0942220c
// flow-typed version: <<STUB>>/@packtracker/webpack-plugin_v2.0.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@packtracker/webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@packtracker/webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@packtracker/webpack-plugin/bin' {
  declare module.exports: any;
}

declare module '@packtracker/webpack-plugin/config' {
  declare module.exports: any;
}

declare module '@packtracker/webpack-plugin/upload' {
  declare module.exports: any;
}

// Filename aliases
declare module '@packtracker/webpack-plugin/bin.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin/bin'>;
}
declare module '@packtracker/webpack-plugin/config.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin/config'>;
}
declare module '@packtracker/webpack-plugin/index' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin'>;
}
declare module '@packtracker/webpack-plugin/index.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin'>;
}
declare module '@packtracker/webpack-plugin/upload.js' {
  declare module.exports: $Exports<'@packtracker/webpack-plugin/upload'>;
}
