// flow-typed signature: 1fb2bc66b6f423cc2da9d1938866dd1f
// flow-typed version: <<STUB>>/apollo-link-ws_v1.0.10/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-ws/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/lib/webSocketLink' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-ws/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/bundle.umd'>;
}
declare module 'apollo-link-ws/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/index'>;
}
declare module 'apollo-link-ws/lib/webSocketLink.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/webSocketLink'>;
}
declare module 'apollo-link-ws/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-ws/rollup.config'>;
}
