// flow-typed signature: b29338b879144953d99daf28791adbdd
// flow-typed version: <<STUB>>/bs-css_v8.0.4/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bs-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bs-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bs-css/lib/js/__tests__/Css_test' {
  declare module.exports: any;
}

declare module 'bs-css/lib/js/src/Css_Colors' {
  declare module.exports: any;
}

declare module 'bs-css/lib/js/src/Css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bs-css/lib/js/__tests__/Css_test.js' {
  declare module.exports: $Exports<'bs-css/lib/js/__tests__/Css_test'>;
}
declare module 'bs-css/lib/js/src/Css_Colors.js' {
  declare module.exports: $Exports<'bs-css/lib/js/src/Css_Colors'>;
}
declare module 'bs-css/lib/js/src/Css.js' {
  declare module.exports: $Exports<'bs-css/lib/js/src/Css'>;
}
