// flow-typed signature: dcf0283f2d129faedf59d3f5b5b2bd5b
// flow-typed version: <<STUB>>/cross-fetch_v3.0.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-fetch/dist/browser-polyfill' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/browser-ponyfill' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/cross-fetch' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/node-polyfill' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/node-ponyfill' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/react-native-polyfill' {
  declare module.exports: any;
}

declare module 'cross-fetch/dist/react-native-ponyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-fetch/dist/browser-polyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/browser-polyfill'>;
}
declare module 'cross-fetch/dist/browser-ponyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/browser-ponyfill'>;
}
declare module 'cross-fetch/dist/cross-fetch.js' {
  declare module.exports: $Exports<'cross-fetch/dist/cross-fetch'>;
}
declare module 'cross-fetch/dist/node-polyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/node-polyfill'>;
}
declare module 'cross-fetch/dist/node-ponyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/node-ponyfill'>;
}
declare module 'cross-fetch/dist/react-native-polyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/react-native-polyfill'>;
}
declare module 'cross-fetch/dist/react-native-ponyfill.js' {
  declare module.exports: $Exports<'cross-fetch/dist/react-native-ponyfill'>;
}
