// flow-typed signature: 2c213b133a54d07a913b1134d62a72cc
// flow-typed version: <<STUB>>/emoji-datasource_v4.1.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-datasource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-datasource' {
  declare module.exports: any;
}
