// flow-typed signature: ec065797cea2e23cb748e3080432d71d
// flow-typed version: <<STUB>>/emotion-server-v9_vnpm:emotion-server@9.2.12/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-server-v9'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-server-v9' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-server-v9/dist/index' {
  declare module.exports: any;
}

declare module 'emotion-server-v9/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-server-v9/dist/index.js' {
  declare module.exports: $Exports<'emotion-server-v9/dist/index'>;
}
declare module 'emotion-server-v9/src/index.js' {
  declare module.exports: $Exports<'emotion-server-v9/src/index'>;
}
