// flow-typed signature: 05255472766fc894f5b0564537bcae65
// flow-typed version: <<STUB>>/emotion-v9_vnpm:emotion@9.2.12/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-v9'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-v9' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-v9/dist/emotion.umd.min' {
  declare module.exports: any;
}

declare module 'emotion-v9/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'emotion-v9/dist/index.esm' {
  declare module.exports: any;
}

declare module 'emotion-v9/macro' {
  declare module.exports: any;
}

declare module 'emotion-v9/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-v9/dist/emotion.umd.min.js' {
  declare module.exports: $Exports<'emotion-v9/dist/emotion.umd.min'>;
}
declare module 'emotion-v9/dist/index.cjs.js' {
  declare module.exports: $Exports<'emotion-v9/dist/index.cjs'>;
}
declare module 'emotion-v9/dist/index.esm.js' {
  declare module.exports: $Exports<'emotion-v9/dist/index.esm'>;
}
declare module 'emotion-v9/macro.js' {
  declare module.exports: $Exports<'emotion-v9/macro'>;
}
declare module 'emotion-v9/src/index.js' {
  declare module.exports: $Exports<'emotion-v9/src/index'>;
}
