// flow-typed signature: e3bb87d5db2e103525333376027c63b9
// flow-typed version: <<STUB>>/emotion-server_v9.2.12/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emotion-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emotion-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emotion-server/dist/index' {
  declare module.exports: any;
}

declare module 'emotion-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emotion-server/dist/index.js' {
  declare module.exports: $Exports<'emotion-server/dist/index'>;
}
declare module 'emotion-server/src/index.js' {
  declare module.exports: $Exports<'emotion-server/src/index'>;
}
