// flow-typed signature: 663b4a7e376649be27e2e844dddce1dc
// flow-typed version: <<STUB>>/execa_v3.2.0/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'execa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'execa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'execa/lib/command' {
  declare module.exports: any;
}

declare module 'execa/lib/error' {
  declare module.exports: any;
}

declare module 'execa/lib/kill' {
  declare module.exports: any;
}

declare module 'execa/lib/promise' {
  declare module.exports: any;
}

declare module 'execa/lib/stdio' {
  declare module.exports: any;
}

declare module 'execa/lib/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'execa/index' {
  declare module.exports: $Exports<'execa'>;
}
declare module 'execa/index.js' {
  declare module.exports: $Exports<'execa'>;
}
declare module 'execa/lib/command.js' {
  declare module.exports: $Exports<'execa/lib/command'>;
}
declare module 'execa/lib/error.js' {
  declare module.exports: $Exports<'execa/lib/error'>;
}
declare module 'execa/lib/kill.js' {
  declare module.exports: $Exports<'execa/lib/kill'>;
}
declare module 'execa/lib/promise.js' {
  declare module.exports: $Exports<'execa/lib/promise'>;
}
declare module 'execa/lib/stdio.js' {
  declare module.exports: $Exports<'execa/lib/stdio'>;
}
declare module 'execa/lib/stream.js' {
  declare module.exports: $Exports<'execa/lib/stream'>;
}
