// flow-typed signature: 671dbfda3d9c2d4f97285eb9a0bda0fc
// flow-typed version: <<STUB>>/firestore-store_v^0.3.4/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firestore-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firestore-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firestore-store/lib/doc-parser' {
  declare module.exports: any;
}

declare module 'firestore-store/lib/firestore-store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firestore-store/index' {
  declare module.exports: $Exports<'firestore-store'>;
}
declare module 'firestore-store/index.js' {
  declare module.exports: $Exports<'firestore-store'>;
}
declare module 'firestore-store/lib/doc-parser.js' {
  declare module.exports: $Exports<'firestore-store/lib/doc-parser'>;
}
declare module 'firestore-store/lib/firestore-store.js' {
  declare module.exports: $Exports<'firestore-store/lib/firestore-store'>;
}
