// flow-typed signature: fd7d7bc5015b0ad3215309eb8578de4e
// flow-typed version: <<STUB>>/jest-emotion-v9_vnpm:jest-emotion@9.2.11/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-emotion-v9'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-emotion-v9' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-emotion-v9/dist/index' {
  declare module.exports: any;
}

declare module 'jest-emotion-v9/serializer' {
  declare module.exports: any;
}

declare module 'jest-emotion-v9/src/index' {
  declare module.exports: any;
}

declare module 'jest-emotion-v9/src/matchers' {
  declare module.exports: any;
}

declare module 'jest-emotion-v9/src/replace-class-names' {
  declare module.exports: any;
}

declare module 'jest-emotion-v9/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-emotion-v9/dist/index.js' {
  declare module.exports: $Exports<'jest-emotion-v9/dist/index'>;
}
declare module 'jest-emotion-v9/serializer.js' {
  declare module.exports: $Exports<'jest-emotion-v9/serializer'>;
}
declare module 'jest-emotion-v9/src/index.js' {
  declare module.exports: $Exports<'jest-emotion-v9/src/index'>;
}
declare module 'jest-emotion-v9/src/matchers.js' {
  declare module.exports: $Exports<'jest-emotion-v9/src/matchers'>;
}
declare module 'jest-emotion-v9/src/replace-class-names.js' {
  declare module.exports: $Exports<'jest-emotion-v9/src/replace-class-names'>;
}
declare module 'jest-emotion-v9/src/utils.js' {
  declare module.exports: $Exports<'jest-emotion-v9/src/utils'>;
}
