// flow-typed signature: f8dfbe922ec87b1716d85c2825be743e
// flow-typed version: <<STUB>>/lru-cache_v5.1.1/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lru-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lru-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lru-cache/index' {
  declare module.exports: $Exports<'lru-cache'>;
}
declare module 'lru-cache/index.js' {
  declare module.exports: $Exports<'lru-cache'>;
}
