// flow-typed signature: f8d3dffe1fbe68ec0752bda25d1bc4f9
// flow-typed version: <<STUB>>/newrelic_v6.0.0/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'newrelic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'newrelic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'newrelic/api' {
  declare module.exports: any;
}

declare module 'newrelic/bin/ca-gen' {
  declare module.exports: any;
}

declare module 'newrelic/bin/compare-bench-results' {
  declare module.exports: any;
}

declare module 'newrelic/bin/run-bench' {
  declare module.exports: any;
}

declare module 'newrelic/bin/test-naming-rules' {
  declare module.exports: any;
}

declare module 'newrelic/lib/adaptive-sampler' {
  declare module.exports: any;
}

declare module 'newrelic/lib/agent' {
  declare module.exports: any;
}

declare module 'newrelic/lib/aggregators/base-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/aggregators/event-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/aggregators/trace-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/attributes' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/api' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/facts' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/http-agents' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/key-parser' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/parse-response' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/remote-method' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/response' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/serverless' {
  declare module.exports: any;
}

declare module 'newrelic/lib/collector/ssl/certificates' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/attribute-filter' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/default' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/env' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/harvest-config-validator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/hsm' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/lasp' {
  declare module.exports: any;
}

declare module 'newrelic/lib/config/merge-server-config' {
  declare module.exports: any;
}

declare module 'newrelic/lib/custom-events/custom-event-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/parse-sql' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/parsed-statement' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/query-parsers/sql' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/query-sample' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/query-trace-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/slow-query' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/statement-matcher' {
  declare module.exports: any;
}

declare module 'newrelic/lib/db/utils' {
  declare module.exports: any;
}

declare module 'newrelic/lib/environment' {
  declare module.exports: any;
}

declare module 'newrelic/lib/errors/error-collector' {
  declare module.exports: any;
}

declare module 'newrelic/lib/errors/error-event-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/errors/error-trace-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/errors/helper' {
  declare module.exports: any;
}

declare module 'newrelic/lib/errors' {
  declare module.exports: any;
}

declare module 'newrelic/lib/feature_flags' {
  declare module.exports: any;
}

declare module 'newrelic/lib/header-attributes' {
  declare module.exports: any;
}

declare module 'newrelic/lib/injector' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/@hapi/hapi' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/amqplib' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/aws-sdk' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/bluebird' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/cassandra-driver' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/connect' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/async_hooks' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/child_process' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/crypto' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/dns' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/domain' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/fs' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/globals' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/http-outbound' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/http' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/inspector' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/net' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/timers' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/core/zlib' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/director' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/express' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/generic-pool' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/hapi' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/hapi/hapi-17' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/hapi/shared' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/ioredis' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/memcached' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/mongodb' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/mysql' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/oracle' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/pg' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/promise' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/q' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/redis' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/restify' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/vision' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentation/when' {
  declare module.exports: any;
}

declare module 'newrelic/lib/instrumentations' {
  declare module.exports: any;
}

declare module 'newrelic/lib/logger' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/mapper' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/metric-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/names' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/normalizer' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/normalizer/rule' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/normalizer/tx_segment' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/custom' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/distributed-trace' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/generic' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/http_external' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/http' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/message-transaction' {
  declare module.exports: any;
}

declare module 'newrelic/lib/metrics/recorders/other' {
  declare module.exports: any;
}

declare module 'newrelic/lib/parse-proc-cpuinfo' {
  declare module.exports: any;
}

declare module 'newrelic/lib/parse-proc-meminfo' {
  declare module.exports: any;
}

declare module 'newrelic/lib/priority-queue' {
  declare module.exports: any;
}

declare module 'newrelic/lib/reservoir' {
  declare module.exports: any;
}

declare module 'newrelic/lib/sampler' {
  declare module.exports: any;
}

declare module 'newrelic/lib/serverless/api-gateway' {
  declare module.exports: any;
}

declare module 'newrelic/lib/serverless/aws-lambda' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/conglomerate-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/constants' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/datastore-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/message-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/promise-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/specs' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/transaction-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shim/webframework-shim' {
  declare module.exports: any;
}

declare module 'newrelic/lib/shimmer' {
  declare module.exports: any;
}

declare module 'newrelic/lib/spans/span-event-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/spans/span-event' {
  declare module.exports: any;
}

declare module 'newrelic/lib/stats/apdex' {
  declare module.exports: any;
}

declare module 'newrelic/lib/stats' {
  declare module.exports: any;
}

declare module 'newrelic/lib/system-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/timer' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/dt-payload' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/handle' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/name-state' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/trace/aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/trace/exclusive-time-calculator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/trace' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/trace/segment' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/tracer' {
  declare module.exports: any;
}

declare module 'newrelic/lib/transaction/transaction-event-aggregator' {
  declare module.exports: any;
}

declare module 'newrelic/lib/uninstrumented' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/arity' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/attribute-types' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/byte-limit' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/cat' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/codec' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/copy' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/deep-equal' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/flatten' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/hashes' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/label-parser' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/logger' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/process-version' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/properties' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/sql/obfuscate' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/stream-sink' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/unwrapped-core' {
  declare module.exports: any;
}

declare module 'newrelic/lib/util/urltils' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/aws-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/azure-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/common' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/docker-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/gcp-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/kubernetes-info' {
  declare module.exports: any;
}

declare module 'newrelic/lib/utilization/pcf-info' {
  declare module.exports: any;
}

declare module 'newrelic/newrelic' {
  declare module.exports: any;
}

declare module 'newrelic/stub_api' {
  declare module.exports: any;
}

// Filename aliases
declare module 'newrelic/api.js' {
  declare module.exports: $Exports<'newrelic/api'>;
}
declare module 'newrelic/bin/ca-gen.js' {
  declare module.exports: $Exports<'newrelic/bin/ca-gen'>;
}
declare module 'newrelic/bin/compare-bench-results.js' {
  declare module.exports: $Exports<'newrelic/bin/compare-bench-results'>;
}
declare module 'newrelic/bin/run-bench.js' {
  declare module.exports: $Exports<'newrelic/bin/run-bench'>;
}
declare module 'newrelic/bin/test-naming-rules.js' {
  declare module.exports: $Exports<'newrelic/bin/test-naming-rules'>;
}
declare module 'newrelic/index' {
  declare module.exports: $Exports<'newrelic'>;
}
declare module 'newrelic/index.js' {
  declare module.exports: $Exports<'newrelic'>;
}
declare module 'newrelic/lib/adaptive-sampler.js' {
  declare module.exports: $Exports<'newrelic/lib/adaptive-sampler'>;
}
declare module 'newrelic/lib/agent.js' {
  declare module.exports: $Exports<'newrelic/lib/agent'>;
}
declare module 'newrelic/lib/aggregators/base-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/aggregators/base-aggregator'>;
}
declare module 'newrelic/lib/aggregators/event-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/aggregators/event-aggregator'>;
}
declare module 'newrelic/lib/aggregators/trace-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/aggregators/trace-aggregator'>;
}
declare module 'newrelic/lib/attributes.js' {
  declare module.exports: $Exports<'newrelic/lib/attributes'>;
}
declare module 'newrelic/lib/collector/api.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/api'>;
}
declare module 'newrelic/lib/collector/facts.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/facts'>;
}
declare module 'newrelic/lib/collector/http-agents.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/http-agents'>;
}
declare module 'newrelic/lib/collector/key-parser.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/key-parser'>;
}
declare module 'newrelic/lib/collector/parse-response.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/parse-response'>;
}
declare module 'newrelic/lib/collector/remote-method.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/remote-method'>;
}
declare module 'newrelic/lib/collector/response.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/response'>;
}
declare module 'newrelic/lib/collector/serverless.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/serverless'>;
}
declare module 'newrelic/lib/collector/ssl/certificates.js' {
  declare module.exports: $Exports<'newrelic/lib/collector/ssl/certificates'>;
}
declare module 'newrelic/lib/config/attribute-filter.js' {
  declare module.exports: $Exports<'newrelic/lib/config/attribute-filter'>;
}
declare module 'newrelic/lib/config/default.js' {
  declare module.exports: $Exports<'newrelic/lib/config/default'>;
}
declare module 'newrelic/lib/config/env.js' {
  declare module.exports: $Exports<'newrelic/lib/config/env'>;
}
declare module 'newrelic/lib/config/harvest-config-validator.js' {
  declare module.exports: $Exports<'newrelic/lib/config/harvest-config-validator'>;
}
declare module 'newrelic/lib/config/hsm.js' {
  declare module.exports: $Exports<'newrelic/lib/config/hsm'>;
}
declare module 'newrelic/lib/config/index' {
  declare module.exports: $Exports<'newrelic/lib/config'>;
}
declare module 'newrelic/lib/config/index.js' {
  declare module.exports: $Exports<'newrelic/lib/config'>;
}
declare module 'newrelic/lib/config/lasp.js' {
  declare module.exports: $Exports<'newrelic/lib/config/lasp'>;
}
declare module 'newrelic/lib/config/merge-server-config.js' {
  declare module.exports: $Exports<'newrelic/lib/config/merge-server-config'>;
}
declare module 'newrelic/lib/custom-events/custom-event-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/custom-events/custom-event-aggregator'>;
}
declare module 'newrelic/lib/db/parse-sql.js' {
  declare module.exports: $Exports<'newrelic/lib/db/parse-sql'>;
}
declare module 'newrelic/lib/db/parsed-statement.js' {
  declare module.exports: $Exports<'newrelic/lib/db/parsed-statement'>;
}
declare module 'newrelic/lib/db/query-parsers/sql.js' {
  declare module.exports: $Exports<'newrelic/lib/db/query-parsers/sql'>;
}
declare module 'newrelic/lib/db/query-sample.js' {
  declare module.exports: $Exports<'newrelic/lib/db/query-sample'>;
}
declare module 'newrelic/lib/db/query-trace-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/db/query-trace-aggregator'>;
}
declare module 'newrelic/lib/db/slow-query.js' {
  declare module.exports: $Exports<'newrelic/lib/db/slow-query'>;
}
declare module 'newrelic/lib/db/statement-matcher.js' {
  declare module.exports: $Exports<'newrelic/lib/db/statement-matcher'>;
}
declare module 'newrelic/lib/db/utils.js' {
  declare module.exports: $Exports<'newrelic/lib/db/utils'>;
}
declare module 'newrelic/lib/environment.js' {
  declare module.exports: $Exports<'newrelic/lib/environment'>;
}
declare module 'newrelic/lib/errors/error-collector.js' {
  declare module.exports: $Exports<'newrelic/lib/errors/error-collector'>;
}
declare module 'newrelic/lib/errors/error-event-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/errors/error-event-aggregator'>;
}
declare module 'newrelic/lib/errors/error-trace-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/errors/error-trace-aggregator'>;
}
declare module 'newrelic/lib/errors/helper.js' {
  declare module.exports: $Exports<'newrelic/lib/errors/helper'>;
}
declare module 'newrelic/lib/errors/index' {
  declare module.exports: $Exports<'newrelic/lib/errors'>;
}
declare module 'newrelic/lib/errors/index.js' {
  declare module.exports: $Exports<'newrelic/lib/errors'>;
}
declare module 'newrelic/lib/feature_flags.js' {
  declare module.exports: $Exports<'newrelic/lib/feature_flags'>;
}
declare module 'newrelic/lib/header-attributes.js' {
  declare module.exports: $Exports<'newrelic/lib/header-attributes'>;
}
declare module 'newrelic/lib/injector.js' {
  declare module.exports: $Exports<'newrelic/lib/injector'>;
}
declare module 'newrelic/lib/instrumentation/@hapi/hapi.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/@hapi/hapi'>;
}
declare module 'newrelic/lib/instrumentation/amqplib.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/amqplib'>;
}
declare module 'newrelic/lib/instrumentation/aws-sdk.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/aws-sdk'>;
}
declare module 'newrelic/lib/instrumentation/bluebird.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/bluebird'>;
}
declare module 'newrelic/lib/instrumentation/cassandra-driver.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/cassandra-driver'>;
}
declare module 'newrelic/lib/instrumentation/connect.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/connect'>;
}
declare module 'newrelic/lib/instrumentation/core/async_hooks.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/async_hooks'>;
}
declare module 'newrelic/lib/instrumentation/core/child_process.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/child_process'>;
}
declare module 'newrelic/lib/instrumentation/core/crypto.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/crypto'>;
}
declare module 'newrelic/lib/instrumentation/core/dns.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/dns'>;
}
declare module 'newrelic/lib/instrumentation/core/domain.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/domain'>;
}
declare module 'newrelic/lib/instrumentation/core/fs.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/fs'>;
}
declare module 'newrelic/lib/instrumentation/core/globals.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/globals'>;
}
declare module 'newrelic/lib/instrumentation/core/http-outbound.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/http-outbound'>;
}
declare module 'newrelic/lib/instrumentation/core/http.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/http'>;
}
declare module 'newrelic/lib/instrumentation/core/inspector.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/inspector'>;
}
declare module 'newrelic/lib/instrumentation/core/net.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/net'>;
}
declare module 'newrelic/lib/instrumentation/core/timers.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/timers'>;
}
declare module 'newrelic/lib/instrumentation/core/zlib.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/core/zlib'>;
}
declare module 'newrelic/lib/instrumentation/director.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/director'>;
}
declare module 'newrelic/lib/instrumentation/express.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/express'>;
}
declare module 'newrelic/lib/instrumentation/generic-pool.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/generic-pool'>;
}
declare module 'newrelic/lib/instrumentation/hapi.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/hapi'>;
}
declare module 'newrelic/lib/instrumentation/hapi/hapi-17.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/hapi/hapi-17'>;
}
declare module 'newrelic/lib/instrumentation/hapi/shared.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/hapi/shared'>;
}
declare module 'newrelic/lib/instrumentation/ioredis.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/ioredis'>;
}
declare module 'newrelic/lib/instrumentation/memcached.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/memcached'>;
}
declare module 'newrelic/lib/instrumentation/mongodb.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/mongodb'>;
}
declare module 'newrelic/lib/instrumentation/mysql.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/mysql'>;
}
declare module 'newrelic/lib/instrumentation/oracle.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/oracle'>;
}
declare module 'newrelic/lib/instrumentation/pg.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/pg'>;
}
declare module 'newrelic/lib/instrumentation/promise.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/promise'>;
}
declare module 'newrelic/lib/instrumentation/q.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/q'>;
}
declare module 'newrelic/lib/instrumentation/redis.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/redis'>;
}
declare module 'newrelic/lib/instrumentation/restify.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/restify'>;
}
declare module 'newrelic/lib/instrumentation/vision.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/vision'>;
}
declare module 'newrelic/lib/instrumentation/when.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentation/when'>;
}
declare module 'newrelic/lib/instrumentations.js' {
  declare module.exports: $Exports<'newrelic/lib/instrumentations'>;
}
declare module 'newrelic/lib/logger.js' {
  declare module.exports: $Exports<'newrelic/lib/logger'>;
}
declare module 'newrelic/lib/metrics/index' {
  declare module.exports: $Exports<'newrelic/lib/metrics'>;
}
declare module 'newrelic/lib/metrics/index.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics'>;
}
declare module 'newrelic/lib/metrics/mapper.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/mapper'>;
}
declare module 'newrelic/lib/metrics/metric-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/metric-aggregator'>;
}
declare module 'newrelic/lib/metrics/names.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/names'>;
}
declare module 'newrelic/lib/metrics/normalizer.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/normalizer'>;
}
declare module 'newrelic/lib/metrics/normalizer/rule.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/normalizer/rule'>;
}
declare module 'newrelic/lib/metrics/normalizer/tx_segment.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/normalizer/tx_segment'>;
}
declare module 'newrelic/lib/metrics/recorders/custom.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/custom'>;
}
declare module 'newrelic/lib/metrics/recorders/distributed-trace.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/distributed-trace'>;
}
declare module 'newrelic/lib/metrics/recorders/generic.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/generic'>;
}
declare module 'newrelic/lib/metrics/recorders/http_external.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/http_external'>;
}
declare module 'newrelic/lib/metrics/recorders/http.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/http'>;
}
declare module 'newrelic/lib/metrics/recorders/message-transaction.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/message-transaction'>;
}
declare module 'newrelic/lib/metrics/recorders/other.js' {
  declare module.exports: $Exports<'newrelic/lib/metrics/recorders/other'>;
}
declare module 'newrelic/lib/parse-proc-cpuinfo.js' {
  declare module.exports: $Exports<'newrelic/lib/parse-proc-cpuinfo'>;
}
declare module 'newrelic/lib/parse-proc-meminfo.js' {
  declare module.exports: $Exports<'newrelic/lib/parse-proc-meminfo'>;
}
declare module 'newrelic/lib/priority-queue.js' {
  declare module.exports: $Exports<'newrelic/lib/priority-queue'>;
}
declare module 'newrelic/lib/reservoir.js' {
  declare module.exports: $Exports<'newrelic/lib/reservoir'>;
}
declare module 'newrelic/lib/sampler.js' {
  declare module.exports: $Exports<'newrelic/lib/sampler'>;
}
declare module 'newrelic/lib/serverless/api-gateway.js' {
  declare module.exports: $Exports<'newrelic/lib/serverless/api-gateway'>;
}
declare module 'newrelic/lib/serverless/aws-lambda.js' {
  declare module.exports: $Exports<'newrelic/lib/serverless/aws-lambda'>;
}
declare module 'newrelic/lib/shim/conglomerate-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/conglomerate-shim'>;
}
declare module 'newrelic/lib/shim/constants.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/constants'>;
}
declare module 'newrelic/lib/shim/datastore-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/datastore-shim'>;
}
declare module 'newrelic/lib/shim/index' {
  declare module.exports: $Exports<'newrelic/lib/shim'>;
}
declare module 'newrelic/lib/shim/index.js' {
  declare module.exports: $Exports<'newrelic/lib/shim'>;
}
declare module 'newrelic/lib/shim/message-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/message-shim'>;
}
declare module 'newrelic/lib/shim/promise-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/promise-shim'>;
}
declare module 'newrelic/lib/shim/shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/shim'>;
}
declare module 'newrelic/lib/shim/specs/index' {
  declare module.exports: $Exports<'newrelic/lib/shim/specs'>;
}
declare module 'newrelic/lib/shim/specs/index.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/specs'>;
}
declare module 'newrelic/lib/shim/transaction-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/transaction-shim'>;
}
declare module 'newrelic/lib/shim/webframework-shim.js' {
  declare module.exports: $Exports<'newrelic/lib/shim/webframework-shim'>;
}
declare module 'newrelic/lib/shimmer.js' {
  declare module.exports: $Exports<'newrelic/lib/shimmer'>;
}
declare module 'newrelic/lib/spans/span-event-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/spans/span-event-aggregator'>;
}
declare module 'newrelic/lib/spans/span-event.js' {
  declare module.exports: $Exports<'newrelic/lib/spans/span-event'>;
}
declare module 'newrelic/lib/stats/apdex.js' {
  declare module.exports: $Exports<'newrelic/lib/stats/apdex'>;
}
declare module 'newrelic/lib/stats/index' {
  declare module.exports: $Exports<'newrelic/lib/stats'>;
}
declare module 'newrelic/lib/stats/index.js' {
  declare module.exports: $Exports<'newrelic/lib/stats'>;
}
declare module 'newrelic/lib/system-info.js' {
  declare module.exports: $Exports<'newrelic/lib/system-info'>;
}
declare module 'newrelic/lib/timer.js' {
  declare module.exports: $Exports<'newrelic/lib/timer'>;
}
declare module 'newrelic/lib/transaction/dt-payload.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/dt-payload'>;
}
declare module 'newrelic/lib/transaction/handle.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/handle'>;
}
declare module 'newrelic/lib/transaction/index' {
  declare module.exports: $Exports<'newrelic/lib/transaction'>;
}
declare module 'newrelic/lib/transaction/index.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction'>;
}
declare module 'newrelic/lib/transaction/name-state.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/name-state'>;
}
declare module 'newrelic/lib/transaction/trace/aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/trace/aggregator'>;
}
declare module 'newrelic/lib/transaction/trace/exclusive-time-calculator.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/trace/exclusive-time-calculator'>;
}
declare module 'newrelic/lib/transaction/trace/index' {
  declare module.exports: $Exports<'newrelic/lib/transaction/trace'>;
}
declare module 'newrelic/lib/transaction/trace/index.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/trace'>;
}
declare module 'newrelic/lib/transaction/trace/segment.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/trace/segment'>;
}
declare module 'newrelic/lib/transaction/tracer/index' {
  declare module.exports: $Exports<'newrelic/lib/transaction/tracer'>;
}
declare module 'newrelic/lib/transaction/tracer/index.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/tracer'>;
}
declare module 'newrelic/lib/transaction/transaction-event-aggregator.js' {
  declare module.exports: $Exports<'newrelic/lib/transaction/transaction-event-aggregator'>;
}
declare module 'newrelic/lib/uninstrumented.js' {
  declare module.exports: $Exports<'newrelic/lib/uninstrumented'>;
}
declare module 'newrelic/lib/util/arity.js' {
  declare module.exports: $Exports<'newrelic/lib/util/arity'>;
}
declare module 'newrelic/lib/util/attribute-types.js' {
  declare module.exports: $Exports<'newrelic/lib/util/attribute-types'>;
}
declare module 'newrelic/lib/util/byte-limit.js' {
  declare module.exports: $Exports<'newrelic/lib/util/byte-limit'>;
}
declare module 'newrelic/lib/util/cat.js' {
  declare module.exports: $Exports<'newrelic/lib/util/cat'>;
}
declare module 'newrelic/lib/util/codec.js' {
  declare module.exports: $Exports<'newrelic/lib/util/codec'>;
}
declare module 'newrelic/lib/util/copy.js' {
  declare module.exports: $Exports<'newrelic/lib/util/copy'>;
}
declare module 'newrelic/lib/util/deep-equal.js' {
  declare module.exports: $Exports<'newrelic/lib/util/deep-equal'>;
}
declare module 'newrelic/lib/util/flatten.js' {
  declare module.exports: $Exports<'newrelic/lib/util/flatten'>;
}
declare module 'newrelic/lib/util/hashes.js' {
  declare module.exports: $Exports<'newrelic/lib/util/hashes'>;
}
declare module 'newrelic/lib/util/label-parser.js' {
  declare module.exports: $Exports<'newrelic/lib/util/label-parser'>;
}
declare module 'newrelic/lib/util/logger.js' {
  declare module.exports: $Exports<'newrelic/lib/util/logger'>;
}
declare module 'newrelic/lib/util/process-version.js' {
  declare module.exports: $Exports<'newrelic/lib/util/process-version'>;
}
declare module 'newrelic/lib/util/properties.js' {
  declare module.exports: $Exports<'newrelic/lib/util/properties'>;
}
declare module 'newrelic/lib/util/sql/obfuscate.js' {
  declare module.exports: $Exports<'newrelic/lib/util/sql/obfuscate'>;
}
declare module 'newrelic/lib/util/stream-sink.js' {
  declare module.exports: $Exports<'newrelic/lib/util/stream-sink'>;
}
declare module 'newrelic/lib/util/unwrapped-core.js' {
  declare module.exports: $Exports<'newrelic/lib/util/unwrapped-core'>;
}
declare module 'newrelic/lib/util/urltils.js' {
  declare module.exports: $Exports<'newrelic/lib/util/urltils'>;
}
declare module 'newrelic/lib/utilization/aws-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/aws-info'>;
}
declare module 'newrelic/lib/utilization/azure-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/azure-info'>;
}
declare module 'newrelic/lib/utilization/common.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/common'>;
}
declare module 'newrelic/lib/utilization/docker-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/docker-info'>;
}
declare module 'newrelic/lib/utilization/gcp-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/gcp-info'>;
}
declare module 'newrelic/lib/utilization/index' {
  declare module.exports: $Exports<'newrelic/lib/utilization'>;
}
declare module 'newrelic/lib/utilization/index.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization'>;
}
declare module 'newrelic/lib/utilization/kubernetes-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/kubernetes-info'>;
}
declare module 'newrelic/lib/utilization/pcf-info.js' {
  declare module.exports: $Exports<'newrelic/lib/utilization/pcf-info'>;
}
declare module 'newrelic/newrelic.js' {
  declare module.exports: $Exports<'newrelic/newrelic'>;
}
declare module 'newrelic/stub_api.js' {
  declare module.exports: $Exports<'newrelic/stub_api'>;
}
