// flow-typed signature: 638ab7771118f2ba6a46968a73b3f825
// flow-typed version: <<STUB>>/next-server_v7.0.2-canary.27/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-server/asset' {
  declare module.exports: any;
}

declare module 'next-server/config' {
  declare module.exports: any;
}

declare module 'next-server/constants' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/asset' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/constants' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/dynamic' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/error-debug' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/EventEmitter' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/head' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/link' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/loadable-capture' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/loadable' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/router/index' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/router/router' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/router/with-router' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/runtime-config' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/shallow-equals' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/side-effect' {
  declare module.exports: any;
}

declare module 'next-server/dist/lib/utils' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/config' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/lib/path-match' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/next-server' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/render' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/require' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/router' {
  declare module.exports: any;
}

declare module 'next-server/dist/server/utils' {
  declare module.exports: any;
}

declare module 'next-server/dynamic' {
  declare module.exports: any;
}

declare module 'next-server/head' {
  declare module.exports: any;
}

declare module 'next-server/link' {
  declare module.exports: any;
}

declare module 'next-server/next-config' {
  declare module.exports: any;
}

declare module 'next-server/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-server/asset.js' {
  declare module.exports: $Exports<'next-server/asset'>;
}
declare module 'next-server/config.js' {
  declare module.exports: $Exports<'next-server/config'>;
}
declare module 'next-server/constants.js' {
  declare module.exports: $Exports<'next-server/constants'>;
}
declare module 'next-server/dist/lib/asset.js' {
  declare module.exports: $Exports<'next-server/dist/lib/asset'>;
}
declare module 'next-server/dist/lib/constants.js' {
  declare module.exports: $Exports<'next-server/dist/lib/constants'>;
}
declare module 'next-server/dist/lib/dynamic.js' {
  declare module.exports: $Exports<'next-server/dist/lib/dynamic'>;
}
declare module 'next-server/dist/lib/error-debug.js' {
  declare module.exports: $Exports<'next-server/dist/lib/error-debug'>;
}
declare module 'next-server/dist/lib/EventEmitter.js' {
  declare module.exports: $Exports<'next-server/dist/lib/EventEmitter'>;
}
declare module 'next-server/dist/lib/head.js' {
  declare module.exports: $Exports<'next-server/dist/lib/head'>;
}
declare module 'next-server/dist/lib/link.js' {
  declare module.exports: $Exports<'next-server/dist/lib/link'>;
}
declare module 'next-server/dist/lib/loadable-capture.js' {
  declare module.exports: $Exports<'next-server/dist/lib/loadable-capture'>;
}
declare module 'next-server/dist/lib/loadable.js' {
  declare module.exports: $Exports<'next-server/dist/lib/loadable'>;
}
declare module 'next-server/dist/lib/router/index.js' {
  declare module.exports: $Exports<'next-server/dist/lib/router/index'>;
}
declare module 'next-server/dist/lib/router/router.js' {
  declare module.exports: $Exports<'next-server/dist/lib/router/router'>;
}
declare module 'next-server/dist/lib/router/with-router.js' {
  declare module.exports: $Exports<'next-server/dist/lib/router/with-router'>;
}
declare module 'next-server/dist/lib/runtime-config.js' {
  declare module.exports: $Exports<'next-server/dist/lib/runtime-config'>;
}
declare module 'next-server/dist/lib/shallow-equals.js' {
  declare module.exports: $Exports<'next-server/dist/lib/shallow-equals'>;
}
declare module 'next-server/dist/lib/side-effect.js' {
  declare module.exports: $Exports<'next-server/dist/lib/side-effect'>;
}
declare module 'next-server/dist/lib/utils.js' {
  declare module.exports: $Exports<'next-server/dist/lib/utils'>;
}
declare module 'next-server/dist/server/config.js' {
  declare module.exports: $Exports<'next-server/dist/server/config'>;
}
declare module 'next-server/dist/server/lib/path-match.js' {
  declare module.exports: $Exports<'next-server/dist/server/lib/path-match'>;
}
declare module 'next-server/dist/server/next-server.js' {
  declare module.exports: $Exports<'next-server/dist/server/next-server'>;
}
declare module 'next-server/dist/server/render.js' {
  declare module.exports: $Exports<'next-server/dist/server/render'>;
}
declare module 'next-server/dist/server/require.js' {
  declare module.exports: $Exports<'next-server/dist/server/require'>;
}
declare module 'next-server/dist/server/router.js' {
  declare module.exports: $Exports<'next-server/dist/server/router'>;
}
declare module 'next-server/dist/server/utils.js' {
  declare module.exports: $Exports<'next-server/dist/server/utils'>;
}
declare module 'next-server/dynamic.js' {
  declare module.exports: $Exports<'next-server/dynamic'>;
}
declare module 'next-server/head.js' {
  declare module.exports: $Exports<'next-server/head'>;
}
declare module 'next-server/index' {
  declare module.exports: $Exports<'next-server'>;
}
declare module 'next-server/index.js' {
  declare module.exports: $Exports<'next-server'>;
}
declare module 'next-server/link.js' {
  declare module.exports: $Exports<'next-server/link'>;
}
declare module 'next-server/next-config.js' {
  declare module.exports: $Exports<'next-server/next-config'>;
}
declare module 'next-server/router.js' {
  declare module.exports: $Exports<'next-server/router'>;
}
