// flow-typed signature: 493d57f377bea4cf7a5f034f5030ba12
// flow-typed version: <<STUB>>/next-offline_v3.2.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-offline/export' {
  declare module.exports: any;
}

declare module 'next-offline/next-manifest' {
  declare module.exports: any;
}

declare module 'next-offline/plugin' {
  declare module.exports: any;
}

declare module 'next-offline/register-sw' {
  declare module.exports: any;
}

declare module 'next-offline/runtime' {
  declare module.exports: any;
}

declare module 'next-offline/service-worker' {
  declare module.exports: any;
}

declare module 'next-offline/tests/forceProd' {
  declare module.exports: any;
}

declare module 'next-offline/tests/next.config' {
  declare module.exports: any;
}

declare module 'next-offline/tests/pages/index' {
  declare module.exports: any;
}

declare module 'next-offline/tests/server' {
  declare module.exports: any;
}

declare module 'next-offline/tests/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-offline/export.js' {
  declare module.exports: $Exports<'next-offline/export'>;
}
declare module 'next-offline/index' {
  declare module.exports: $Exports<'next-offline'>;
}
declare module 'next-offline/index.js' {
  declare module.exports: $Exports<'next-offline'>;
}
declare module 'next-offline/next-manifest.js' {
  declare module.exports: $Exports<'next-offline/next-manifest'>;
}
declare module 'next-offline/plugin.js' {
  declare module.exports: $Exports<'next-offline/plugin'>;
}
declare module 'next-offline/register-sw.js' {
  declare module.exports: $Exports<'next-offline/register-sw'>;
}
declare module 'next-offline/runtime.js' {
  declare module.exports: $Exports<'next-offline/runtime'>;
}
declare module 'next-offline/service-worker.js' {
  declare module.exports: $Exports<'next-offline/service-worker'>;
}
declare module 'next-offline/tests/forceProd.js' {
  declare module.exports: $Exports<'next-offline/tests/forceProd'>;
}
declare module 'next-offline/tests/next.config.js' {
  declare module.exports: $Exports<'next-offline/tests/next.config'>;
}
declare module 'next-offline/tests/pages/index.js' {
  declare module.exports: $Exports<'next-offline/tests/pages/index'>;
}
declare module 'next-offline/tests/server.js' {
  declare module.exports: $Exports<'next-offline/tests/server'>;
}
declare module 'next-offline/tests/test.js' {
  declare module.exports: $Exports<'next-offline/tests/test'>;
}
