// flow-typed signature: 158d4e3146ab3c1bf0a65e50e1f9635f
// flow-typed version: <<STUB>>/opn_v5.4.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'opn/index' {
  declare module.exports: $Exports<'opn'>;
}
declare module 'opn/index.js' {
  declare module.exports: $Exports<'opn'>;
}
