// flow-typed signature: 704ea9d07d1bf1c44044b15d5d91e074
// flow-typed version: <<STUB>>/reason-react_v0.5.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reason-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reason-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reason-react/lib/js/src/ReactDOMRe' {
  declare module.exports: any;
}

declare module 'reason-react/lib/js/src/ReactDOMServerRe' {
  declare module.exports: any;
}

declare module 'reason-react/lib/js/src/ReactEvent' {
  declare module.exports: any;
}

declare module 'reason-react/lib/js/src/ReactEventRe' {
  declare module.exports: any;
}

declare module 'reason-react/lib/js/src/ReasonReact' {
  declare module.exports: any;
}

declare module 'reason-react/lib/js/src/ReasonReactOptimizedCreateClass' {
  declare module.exports: any;
}

declare module 'reason-react/migrate/from015To020' {
  declare module.exports: any;
}

declare module 'reason-react/migrate/from02xTo024' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reason-react/lib/js/src/ReactDOMRe.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReactDOMRe'>;
}
declare module 'reason-react/lib/js/src/ReactDOMServerRe.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReactDOMServerRe'>;
}
declare module 'reason-react/lib/js/src/ReactEvent.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReactEvent'>;
}
declare module 'reason-react/lib/js/src/ReactEventRe.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReactEventRe'>;
}
declare module 'reason-react/lib/js/src/ReasonReact.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReasonReact'>;
}
declare module 'reason-react/lib/js/src/ReasonReactOptimizedCreateClass.js' {
  declare module.exports: $Exports<'reason-react/lib/js/src/ReasonReactOptimizedCreateClass'>;
}
declare module 'reason-react/migrate/from015To020.js' {
  declare module.exports: $Exports<'reason-react/migrate/from015To020'>;
}
declare module 'reason-react/migrate/from02xTo024.js' {
  declare module.exports: $Exports<'reason-react/migrate/from02xTo024'>;
}
