// flow-typed signature: 2db8cd3631d4a86d87a793c39c6f8fc9
// flow-typed version: <<STUB>>/sanitize.css_v9.0.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
