// flow-typed signature: 40e8513757eab159ec41831542c8fdd9
// flow-typed version: <<STUB>>/sanitize.css_v7.0.3/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
