// flow-typed signature: 27cfdda400b5607f31b0be26d1463ba5
// flow-typed version: <<STUB>>/sanitize.css_v8.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
