// flow-typed signature: b35d2fb7d90d195c2b4736a5daf976e7
// flow-typed version: <<STUB>>/screenfull_v4.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'screenfull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'screenfull' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'screenfull/dist/screenfull' {
  declare module.exports: any;
}

// Filename aliases
declare module 'screenfull/dist/screenfull.js' {
  declare module.exports: $Exports<'screenfull/dist/screenfull'>;
}
