// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Link$SimonKjellberg from "./Link.bs.js";
import * as Next$SimonKjellberg from "../bindings/Next.bs.js";
import * as Heading$SimonKjellberg from "./Heading.bs.js";
import * as Subtitle$SimonKjellberg from "./Subtitle.bs.js";

function str(prim) {
  return prim;
}

var config = Next$SimonKjellberg.Config.getConfig(undefined);

function About(Props) {
  return React.createElement("section", undefined, React.createElement(Heading$SimonKjellberg.make, {
                  level: /* Level2 */-656133554,
                  children: null
                }, "About ", React.createElement(Subtitle$SimonKjellberg.make, {
                      children: "(Location: Stockholm, Sweden)"
                    })), React.createElement("p", undefined, config.publicRuntimeConfig.siteDescription), React.createElement("p", undefined, "Working as a web engineer at ", React.createElement(Link$SimonKjellberg.make, {
                      href: "https://twitter.com/SpotifyEng",
                      target: "_blank",
                      rel: "noopener noreferrer",
                      children: "Spotify"
                    }), "."));
}

var make = About;

var $$default = About;

export {
  str ,
  config ,
  make ,
  $$default ,
  $$default as default,
  
}
/* config Not a pure module */
