// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Link$SimonKjellberg from "./Link.bs.js";
import * as Next$SimonKjellberg from "../bindings/Next.bs.js";
import * as Heading$SimonKjellberg from "./Heading.bs.js";
import * as Subtitle$SimonKjellberg from "./Subtitle.bs.js";

function str(prim) {
  return prim;
}

var config = Next$SimonKjellberg.Config[/* getConfig */0](/* () */0);

var component = ReasonReact.statelessComponent("About");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("section", undefined, ReasonReact.element(undefined, undefined, Heading$SimonKjellberg.make(/* Level2 */-656133554, /* array */[
                                  "About ",
                                  ReasonReact.element(undefined, undefined, Subtitle$SimonKjellberg.make(/* array */["(Location: Stockholm, Sweden)"]))
                                ])), React.createElement("p", undefined, config.publicRuntimeConfig.siteDescription), React.createElement("p", undefined, "Working as a consultant via my own company, ", ReasonReact.element(undefined, undefined, Link$SimonKjellberg.make("https://shebang.consulting", /* array */["Shebang"])), "."));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

export {
  str ,
  config ,
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* config Not a pure module */
