// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Theme$SimonKjellberg from "../Theme.bs.js";

var styles = Css.style(/* :: */[
      Css.position(/* relative */903134412),
      /* :: */[
        Css.marginTop(Css.em(1.0)),
        /* :: */[
          Css.marginBottom(Css.em(1.0)),
          /* :: */[
            Css.marginLeft(Css.ch(1.5)),
            /* :: */[
              Css.fontSize(Css.rem(1.0)),
              /* :: */[
                Css.fontWeight(/* bold */-1055161979),
                /* :: */[
                  Css.before(/* :: */[
                        Css.position(/* absolute */-1013592457),
                        /* :: */[
                          Css.left(Css.ch(-1.5)),
                          /* :: */[
                            Css.contentRule(">"),
                            /* :: */[
                              Css.color(Theme$SimonKjellberg.Color[/* muted */2]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var component = ReasonReact.statelessComponent("Heading");

function make(level, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReactDOMRe.createElementVariadic("h" + (
                          level >= -656133552 ? (
                              level >= -656133550 ? (
                                  level >= -656133549 ? "1" : "6"
                                ) : (
                                  level >= -656133551 ? "5" : "4"
                                )
                            ) : (
                              level >= -656133554 ? (
                                  level >= -656133553 ? "3" : "2"
                                ) : "1"
                            )
                        ), {
                          className: styles
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        var match = jsProps.level;
        var tmp;
        switch (match) {
          case "1" : 
              tmp = /* Level1 */-656133555;
              break;
          case "2" : 
              tmp = /* Level2 */-656133554;
              break;
          case "3" : 
              tmp = /* Level3 */-656133553;
              break;
          case "4" : 
              tmp = /* Level4 */-656133552;
              break;
          case "5" : 
              tmp = /* Level5 */-656133551;
              break;
          case "6" : 
              tmp = /* Level6 */-656133550;
              break;
          default:
            tmp = /* Level1 */-656133555;
        }
        return make(tmp, jsProps.children);
      }));

export {
  styles ,
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
