// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Link$SimonKjellberg from "./Link.bs.js";
import * as Utils$SimonKjellberg from "../Utils.bs.js";
import * as Heading$SimonKjellberg from "./Heading.bs.js";
import * as UnorderedList$SimonKjellberg from "./UnorderedList.bs.js";
import * as UnorderedListItem$SimonKjellberg from "./UnorderedListItem.bs.js";

var component = ReasonReact.statelessComponent("Links");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("section", undefined, ReasonReact.element(undefined, undefined, Heading$SimonKjellberg.make(/* Level2 */-656133554, /* array */[Utils$SimonKjellberg.str("Links")])), ReasonReact.element(undefined, undefined, UnorderedList$SimonKjellberg.make(undefined, undefined, /* array */[
                                  ReasonReact.element(undefined, undefined, UnorderedListItem$SimonKjellberg.make(undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, Link$SimonKjellberg.make("https://github.com/simonkberg", undefined, undefined, /* array */[Utils$SimonKjellberg.str("GitHub")]))])),
                                  ReasonReact.element(undefined, undefined, UnorderedListItem$SimonKjellberg.make(undefined, undefined, /* array */[ReasonReact.element(undefined, undefined, Link$SimonKjellberg.make("https://linkedin.com/in/simonkjellberg", undefined, undefined, /* array */[Utils$SimonKjellberg.str("LinkedIn")]))]))
                                ])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (_jsProps) {
        return make(/* array */[]);
      }));

export {
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* component Not a pure module */
