// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Next$SimonKjellberg from "../bindings/Next.bs.js";
import * as Theme$SimonKjellberg from "../Theme.bs.js";
import * as Utils$SimonKjellberg from "../Utils.bs.js";
import * as Header$SimonKjellberg from "./Header.bs.js";

var wrapper = Css.style(/* :: */[
      Css.fontSize(Css.pct(100.0)),
      /* :: */[
        Css.lineHeight(/* `abs */[
              4845682,
              1.5
            ]),
        /* :: */[
          Css.fontFamily("Iosevka, monospace"),
          /* :: */[
            Css.color(Theme$SimonKjellberg.Color[/* primary */0]),
            /* [] */0
          ]
        ]
      ]
    ]);

var content = Css.style(/* :: */[
      Css.margin2(/* zero */-789508312, /* auto */-1065951377),
      /* :: */[
        Css.maxWidth(Theme$SimonKjellberg.Page[/* maxWidth */0]),
        /* :: */[
          Css.padding3(/* zero */-789508312, Css.rem(0.9375), Css.rem(1.875)),
          /* :: */[
            Css.unsafe("@supports(padding: max(0px)) and (padding: env(safe-area-inset-bottom))", Css.style(/* :: */[
                      Css.unsafe("padding-left", "max(env(safe-area-inset-left), 0.9375rem)"),
                      /* :: */[
                        Css.unsafe("padding-right", "max(env(safe-area-inset-right), 0.9375rem)"),
                        /* :: */[
                          Css.unsafe("padding-bottom", "max(env(safe-area-inset-bottom), 1.875rem)"),
                          /* [] */0
                        ]
                      ]
                    ])),
            /* [] */0
          ]
        ]
      ]
    ]);

var Styles = /* module */[
  /* wrapper */wrapper,
  /* content */content
];

var component = ReasonReact.statelessComponent("Link");

function make($staropt$star, $staropt$star$1, children) {
  var siteTitle = $staropt$star !== undefined ? $staropt$star : "Simon Kjellberg";
  var siteDescription = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", {
                          className: wrapper
                        }, ReasonReact.element(undefined, undefined, Next$SimonKjellberg.Head[/* make */0](/* array */[
                                  React.createElement("title", undefined, Utils$SimonKjellberg.str(siteTitle)),
                                  React.createElement("meta", {
                                        content: siteDescription,
                                        property: "og:title"
                                      }),
                                  React.createElement("meta", {
                                        content: siteDescription,
                                        name: "description",
                                        property: "og:description"
                                      })
                                ])), ReasonReact.element(undefined, undefined, Header$SimonKjellberg.make(siteTitle, /* array */[])), ReactDOMRe.createElementVariadic("div", {
                              className: content
                            }, children));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.siteTitle, jsProps.siteDescription, jsProps.children);
      }));

export {
  Styles ,
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* wrapper Not a pure module */
