// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Theme$SimonKjellberg from "../Theme.bs.js";

var styles = Css.style(/* :: */[
      Css.color(Theme$SimonKjellberg.Color[/* muted */2]),
      /* :: */[
        Css.fontWeight(/* normal */812216871),
        /* [] */0
      ]
    ]);

var component = ReasonReact.statelessComponent("Subtitle");

function make(children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return ReactDOMRe.createElementVariadic("small", {
                          className: styles
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.children);
      }));

export {
  styles ,
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
