// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Utils$SimonKjellberg from "../Utils.bs.js";

var styles = Css.style(/* :: */[
      Css.listStyleType(/* none */-922086728),
      /* :: */[
        Css.padding(Css.zero),
        /* :: */[
          Css.marginTop(Css.em(1.0)),
          /* :: */[
            Css.marginBottom(Css.em(1.0)),
            /* :: */[
              Css.marginLeft(Css.ch(1.5)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var component = ReasonReact.statelessComponent("UnorderedList");

function make(className, innerRef, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              var tmp = {
                className: Utils$SimonKjellberg.cn(/* :: */[
                      styles,
                      /* :: */[
                        Utils$SimonKjellberg.$pipe$unknown(className, ""),
                        /* [] */0
                      ]
                    ])
              };
              if (innerRef !== undefined) {
                tmp.ref = Caml_option.valFromOption(innerRef);
              }
              return ReactDOMRe.createElementVariadic("ul", Caml_option.some(tmp), children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var $$default = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(Caml_option.nullable_to_opt(jsProps.className), Caml_option.nullable_to_opt(jsProps.innerRef), jsProps.children);
      }));

export {
  styles ,
  component ,
  make ,
  $$default ,
  $$default as default,
  
}
/* styles Not a pure module */
