// flow-typed signature: f52d1c3c97c3990f9540e22a42a05cf1
// flow-typed version: <<STUB>>/@apollo/react-ssr_v3.1.3/flow_v0.111.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@apollo/react-ssr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@apollo/react-ssr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@apollo/react-ssr/lib/getDataFromTree' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib/react-ssr.cjs' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib/react-ssr.cjs.min' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib/react-ssr.esm' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib/react-ssr.umd' {
  declare module.exports: any;
}

declare module '@apollo/react-ssr/lib/renderToStringWithData' {
  declare module.exports: any;
}

// Filename aliases
declare module '@apollo/react-ssr/lib/getDataFromTree.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/getDataFromTree'>;
}
declare module '@apollo/react-ssr/lib/index' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib'>;
}
declare module '@apollo/react-ssr/lib/index.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib'>;
}
declare module '@apollo/react-ssr/lib/react-ssr.cjs.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/react-ssr.cjs'>;
}
declare module '@apollo/react-ssr/lib/react-ssr.cjs.min.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/react-ssr.cjs.min'>;
}
declare module '@apollo/react-ssr/lib/react-ssr.esm.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/react-ssr.esm'>;
}
declare module '@apollo/react-ssr/lib/react-ssr.umd.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/react-ssr.umd'>;
}
declare module '@apollo/react-ssr/lib/renderToStringWithData.js' {
  declare module.exports: $Exports<'@apollo/react-ssr/lib/renderToStringWithData'>;
}
