// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css-emotion/src/Css.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Js_exn from "bs-platform/lib/es6/js_exn.js";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function str(prim) {
  return prim;
}

function dangerousHtml(html) {
  return {
          __html: html
        };
}

function forwardDOMRef(fn) {
  return React.forwardRef((function (props, ref_) {
                return Curry._2(fn, props, Belt_Option.map((ref_ == null) ? undefined : Caml_option.some(ref_), (function (prim) {
                                  return prim;
                                })));
              }));
}

function $great$great$eq(value, fn) {
  if (value !== undefined) {
    return Curry._1(fn, Caml_option.valFromOption(value));
  }
  
}

function $pipe$question(value, $$default) {
  if (value !== undefined) {
    return Caml_option.valFromOption(value);
  } else {
    return $$default;
  }
}

function cn(cns) {
  return $$String.concat(" ", Belt_List.keep(cns, (function (x) {
                    return x !== "";
                  })));
}

function string_of_float(prim) {
  return prim.toString();
}

function string_of_int(prim) {
  return prim.toString();
}

function string_of_angle(param) {
  var variant = param[0];
  if (variant >= 4995526) {
    if (variant >= 5690837) {
      return param[1].toString() + "rad";
    } else {
      return param[1].toString() + "deg";
    }
  } else if (variant >= -855250051) {
    return param[1].toString() + "turn";
  } else {
    return param[1].toString() + "grad";
  }
}

function string_of_percent(param) {
  return param[1].toString() + "%";
}

function string_of_alpha(param) {
  if (param[0] >= 5496390) {
    return param[1].toString();
  } else {
    return param[1].toString() + "%";
  }
}

function string_of_rgb(r, g, b) {
  return "rgb(" + (r.toString() + (", " + (g.toString() + (", " + (b.toString() + ")")))));
}

function rgb_of_string(s) {
  var re = s.match(/^rgb\((\d+), ?(\d+), ?(\d+)\)/);
  if (re !== null) {
    return Css.rgb(Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 1)), Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 2)), Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 3)));
  } else {
    return Js_exn.raiseError("Invalid formatted value");
  }
}

function string_of_rgba(r, g, b, a) {
  return "rgba(" + (r.toString() + (", " + (g.toString() + (", " + (b.toString() + (", " + (a.toString() + ")")))))));
}

function rgba_of_string(s) {
  var re = s.match(/^rgba\((\d+), ?(\d+), ?(\d+), ?([\d.]+)\)/);
  if (re !== null) {
    return Css.rgba(Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 1)), Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 2)), Caml_format.caml_int_of_string(Caml_array.caml_array_get(re, 3)), Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 4)));
  } else {
    return Js_exn.raiseError("Invalid formatted value");
  }
}

function string_of_hsl(h, s, l) {
  return "hsl(" + (string_of_angle(h) + (", " + (string_of_percent(s) + (", " + (string_of_percent(l) + ")")))));
}

function hsl_of_string(s) {
  var re = s.match(/^hsl\((\d+), ?(\d+)%, ?(\d+)%\)/);
  if (re !== null) {
    return Css.hsl(/* `deg */[
                4995526,
                Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 1))
              ], Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 2)), Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 3)));
  } else {
    return Js_exn.raiseError("Invalid formatted value");
  }
}

function string_of_hsla(h, s, l, a) {
  return "hsla(" + (string_of_angle(h) + (", " + (string_of_percent(s) + (", " + (string_of_percent(l) + (", " + (string_of_alpha(a) + ")")))))));
}

function hsla_of_string(s) {
  var re = s.match(/^hsl\((\d+), ?(\d+)%, ?(\d+)%, ?([\d.]+)\)/);
  if (re !== null) {
    return Css.hsla(/* `deg */[
                4995526,
                Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 1))
              ], Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 2)), Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 3)), /* `percent */[
                -119887163,
                Caml_format.caml_float_of_string(Caml_array.caml_array_get(re, 4))
              ]);
  } else {
    return Js_exn.raiseError("Invalid formatted value");
  }
}

function string_of_color(param) {
  if (typeof param === "number") {
    if (param >= 582626130) {
      return "transparent";
    } else {
      return "currentColor";
    }
  }
  var variant = param[0];
  if (variant !== -878128972) {
    if (variant >= 5197569) {
      if (variant >= 5692173) {
        var match = param[1];
        return string_of_rgb(match[0], match[1], match[2]);
      }
      var match$1 = param[1];
      return string_of_hsl(match$1[0], match$1[1], match$1[2]);
    }
    if (variant >= 5194459) {
      return "#" + param[1];
    }
    var match$2 = param[1];
    return string_of_hsla(match$2[0], match$2[1], match$2[2], match$2[3]);
  }
  var match$3 = param[1];
  return string_of_rgba(match$3[0], match$3[1], match$3[2], match$3[3]);
}

function color_of_string(s) {
  if (s.startsWith("rgb(")) {
    return rgb_of_string(s);
  } else if (s.startsWith("rgba(") || s.startsWith("rgba(")) {
    return rgba_of_string(s);
  } else if (s.startsWith("#")) {
    return Css.hex(s.slice(1));
  } else if (s === "transparent") {
    return Css.transparent;
  } else if (s === "currentColor") {
    return Css.currentColor;
  } else {
    return Js_exn.raiseError("Invalid value");
  }
}

function string_of_length(param) {
  if (typeof param === "number") {
    return "0";
  }
  var variant = param[0];
  if (variant >= 22632) {
    if (variant >= 25096) {
      if (variant >= 26433) {
        if (variant >= 5691738) {
          return param[1].toString() + "rem";
        } else {
          return param[1].toString() + "vw";
        }
      } else if (variant >= 26418) {
        return param[1].toString() + "vh";
      } else {
        return param[1].toString() + "px";
      }
    } else if (variant >= 24416) {
      if (variant >= 25092) {
        return param[1].toString() + "pt";
      } else {
        return param[1].toString() + "mm";
      }
    } else if (variant >= 22643) {
      return param[1].toString() + "ex";
    } else {
      return param[1].toString() + "em";
    }
  }
  if (variant >= -833470756) {
    if (variant >= 22181) {
      if (variant >= 22186) {
        return param[1].toString() + "cm";
      } else {
        return param[1].toString() + "ch";
      }
    } else if (variant >= -119887163) {
      return param[1].toString() + "%";
    } else {
      return param[1].toString() + "vmin";
    }
  }
  if (variant === -1040484748) {
    return param[1].toString() + "px";
  }
  if (variant >= -833472530) {
    return param[1].toString() + "vmax";
  }
  var match = param[1];
  if (match[0] >= 5745024) {
    return "calc(" + (string_of_length(match[1]) + (" - " + (string_of_length(match[2]) + ")")));
  } else {
    return "calc(" + (string_of_length(match[1]) + (" + " + (string_of_length(match[2]) + ")")));
  }
}

function string_of_minmax(param) {
  if (typeof param === "number") {
    if (param >= -550577721) {
      if (param >= 60557045) {
        return "max-content";
      } else {
        return "min-content";
      }
    } else if (param >= -789508312) {
      return "0";
    } else {
      return "auto";
    }
  }
  var variant = param[0];
  if (variant >= 22643) {
    if (variant >= 25096) {
      if (variant >= 26433) {
        if (variant >= 5691738) {
          return param[1].toString() + "rem";
        } else {
          return param[1].toString() + "vw";
        }
      } else if (variant >= 26418) {
        return param[1].toString() + "vh";
      } else {
        return param[1].toString() + "px";
      }
    } else if (variant >= 24416) {
      if (variant >= 25092) {
        return param[1].toString() + "pt";
      } else {
        return param[1].toString() + "mm";
      }
    } else if (variant >= 22860) {
      return param[1].toString() + "fr";
    } else {
      return param[1].toString() + "ex";
    }
  }
  if (variant >= -119887163) {
    if (variant >= 22186) {
      if (variant >= 22632) {
        return param[1].toString() + "em";
      } else {
        return param[1].toString() + "cm";
      }
    } else if (variant >= 22181) {
      return param[1].toString() + "ch";
    } else {
      return param[1].toString() + "%";
    }
  }
  if (variant >= -833472530) {
    if (variant >= -833470756) {
      return param[1].toString() + "vmin";
    } else {
      return param[1].toString() + "vmax";
    }
  }
  if (variant >= -1040484748) {
    return param[1].toString() + "px";
  }
  var match = param[1];
  if (match[0] >= 5745024) {
    return "calc(" + (string_of_length(match[1]) + (" - " + (string_of_length(match[2]) + ")")));
  } else {
    return "calc(" + (string_of_length(match[1]) + (" + " + (string_of_length(match[2]) + ")")));
  }
}

function string_of_dimension(param) {
  if (typeof param === "number") {
    if (param !== -922086728) {
      if (param >= -550577721) {
        if (param >= 60557045) {
          return "max-content";
        } else {
          return "min-content";
        }
      } else if (param >= -789508312) {
        return "0";
      } else {
        return "auto";
      }
    } else {
      return "none";
    }
  }
  var variant = param[0];
  if (variant >= 22632) {
    if (variant >= 25092) {
      if (variant !== 25096) {
        if (variant >= 26433) {
          if (variant >= 5691738) {
            return param[1].toString() + "rem";
          } else {
            return param[1].toString() + "vw";
          }
        } else if (variant >= 26418) {
          return param[1].toString() + "vh";
        } else {
          return param[1].toString() + "pt";
        }
      } else {
        return param[1].toString() + "px";
      }
    } else if (variant >= 22860) {
      if (variant >= 24416) {
        return param[1].toString() + "mm";
      } else {
        return param[1].toString() + "fr";
      }
    } else if (variant >= 22643) {
      return param[1].toString() + "ex";
    } else {
      return param[1].toString() + "em";
    }
  }
  if (variant >= -754859950) {
    if (variant >= 22181) {
      if (variant >= 22186) {
        return param[1].toString() + "cm";
      } else {
        return param[1].toString() + "ch";
      }
    }
    if (variant >= -119887163) {
      return param[1].toString() + "%";
    }
    var match = param[1];
    return "minmax(" + (string_of_minmax(match[0]) + ("," + (string_of_minmax(match[1]) + ")")));
  }
  if (variant >= -833472530) {
    if (variant >= -833470756) {
      return param[1].toString() + "vmin";
    } else {
      return param[1].toString() + "vmax";
    }
  }
  if (variant >= -1040484748) {
    return param[1].toString() + "px";
  }
  var match$1 = param[1];
  if (match$1[0] >= 5745024) {
    return "calc(" + (string_of_length(match$1[1]) + (" - " + (string_of_length(match$1[2]) + ")")));
  } else {
    return "calc(" + (string_of_length(match$1[1]) + (" + " + (string_of_length(match$1[2]) + ")")));
  }
}

export {
  str ,
  dangerousHtml ,
  forwardDOMRef ,
  $great$great$eq ,
  $pipe$question ,
  cn ,
  string_of_float ,
  string_of_int ,
  string_of_angle ,
  string_of_percent ,
  string_of_alpha ,
  string_of_rgb ,
  rgb_of_string ,
  string_of_rgba ,
  rgba_of_string ,
  string_of_hsl ,
  hsl_of_string ,
  string_of_hsla ,
  hsla_of_string ,
  string_of_color ,
  color_of_string ,
  string_of_length ,
  string_of_minmax ,
  string_of_dimension ,
  
}
/* Css Not a pure module */
