// flow-typed signature: e24bcac3187c7780f344cc4a955323bb
// flow-typed version: <<STUB>>/@simonkberg/eslint-config_v11.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@simonkberg/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@simonkberg/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@simonkberg/eslint-config/flowtype' {
  declare module.exports: any;
}

declare module '@simonkberg/eslint-config/react' {
  declare module.exports: any;
}

// Filename aliases
declare module '@simonkberg/eslint-config/flowtype.js' {
  declare module.exports: $Exports<'@simonkberg/eslint-config/flowtype'>;
}
declare module '@simonkberg/eslint-config/index' {
  declare module.exports: $Exports<'@simonkberg/eslint-config'>;
}
declare module '@simonkberg/eslint-config/index.js' {
  declare module.exports: $Exports<'@simonkberg/eslint-config'>;
}
declare module '@simonkberg/eslint-config/react.js' {
  declare module.exports: $Exports<'@simonkberg/eslint-config/react'>;
}
