// flow-typed signature: 770a8ba912e3a35350e879ad63aa63e2
// flow-typed version: <<STUB>>/@simonkberg/reason-apollo_v0.15.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@simonkberg/reason-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@simonkberg/reason-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@simonkberg/reason-apollo/src/ApolloClient.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ApolloConsumer.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ApolloInMemoryCache.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ApolloLinks.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ApolloProvider.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ApolloUtilities.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloMutation.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloQuery.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloSubscription.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ReasonApollo.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ReasonApolloTypes.bs' {
  declare module.exports: any;
}

declare module '@simonkberg/reason-apollo/src/ReasonApolloUtils.bs' {
  declare module.exports: any;
}

// Filename aliases
declare module '@simonkberg/reason-apollo/src/ApolloClient.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloClient.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ApolloConsumer.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloConsumer.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ApolloInMemoryCache.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloInMemoryCache.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ApolloLinks.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloLinks.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ApolloProvider.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloProvider.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ApolloUtilities.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ApolloUtilities.bs'>;
}
declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloMutation.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/graphql-types/ReasonApolloMutation.bs'>;
}
declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloQuery.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/graphql-types/ReasonApolloQuery.bs'>;
}
declare module '@simonkberg/reason-apollo/src/graphql-types/ReasonApolloSubscription.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/graphql-types/ReasonApolloSubscription.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ReasonApollo.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ReasonApollo.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ReasonApolloTypes.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ReasonApolloTypes.bs'>;
}
declare module '@simonkberg/reason-apollo/src/ReasonApolloUtils.bs.js' {
  declare module.exports: $Exports<'@simonkberg/reason-apollo/src/ReasonApolloUtils.bs'>;
}
